### ISSUE TITLE
Add an option to turn off ID tracking on BaseTable

### ISSUE THREAD

**Issue by tburry** [initvector/vanilla-colonize#2]
You should add a way to not track IDs on tables and then turn it off for comments. I ran out of memory during my import.

**Comment by initvector** [comment]
Added a proper to BaseTable that determines whether or not inserted rows should be tracked.  The default value is true/on, but it is disabled in Comments.  Initial implementation here: 4fa24a6491422791963320e0f56c4877d3cf995e
