### ISSUE TITLE
Optimize BaseTable->getRandomId()

### ISSUE THREAD

**Issue by tburry** [initvector/vanilla-colonize#4]
See my comment [here](https://github.com/initvector/vanilla-colonize/commit/1fe71010e3d87295d9c6f6d307af2d881e41a187#diff-3c7c7b56ec7f75f2ae4fe674ce4bb7ccR108). Also make sure to account for an empty ID array.

**Comment by initvector** [comment]
I swapped out array_rand for count + rand.  Implementation is here: 4fa24a6491422791963320e0f56c4877d3cf995e
