### ISSUE TITLE
Add times and counts for each table.

### ISSUE THREAD

**Issue by tburry** [initvector/vanilla-colonize#5]
Since we are also using this tool to check for speed can you output a bit more information when a table is finished? I'm thinking something like "x rows in y s" type of thing.

**Comment by initvector** [comment]
I rewrote progress tracking.  There's no more dots!  It's now a current/total display.  As part of this rewrite, I added per-section timekeeping.  Implementation is here: e6796fabe1bbc715b84097e686d0b65b34608a66

**Comment by tburry** [comment]
Very nice!
